# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: 
      echo "export AWS_ACCESS_KEY_ID=\$AWS_ACCESS_KEY_ID" >> ~/.bashrc
      echo "export AWS_SECRET_ACCESS_KEY=\$AWS_SECRET_ACCESS_KEY" >> ~/.bashrc
      echo "export AWS_DEFAULT_REGION=\$AWS_DEFAULT_REGION" >> ~/.bashrc
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT